# Comprehensive list of airlines for dropdown
# Generated automatically - do not edit manually

AIRLINES_LIST = [
    "AA – American Airlines",
    "AC – Air Canada", 
    "AF – Air France",
    "AI – Air India",
    "AM – Aeromexico",
    "AR – Aerolineas Argentinas",
    "AS – Alaska Airlines",
    "AV – Avianca",
    "AY – Finnair",
    "AZ – ITA Airways",
    "BA – British Airways",
    "BD – British Midland International",
    "BI – Royal Brunei Airlines",
    "BR – EVA Air",
    "CA – Air China",
    "CI – China Airlines",
    "CO – Continental Airlines",
    "CX – Cathay Pacific",
    "CZ – China Southern Airlines",
    "DL – Delta Air Lines",
    "EK – Emirates",
    "ET – Ethiopian Airlines",
    "EY – Etihad Airways",
    "FI – Icelandair",
    "FJ – Fiji Airways",
    "FL – AirTran Airways",
    "GA – Garuda Indonesia",
    "GF – Gulf Air",
    "HA – Hawaiian Airlines",
    "IB – Iberia",
    "IC – Indian Airlines",
    "JL – Japan Airlines",
    "JM – Air Jamaica",
    "JP – Adria Airways",
    "KA – Dragonair",
    "KE – Korean Air",
    "KL – KLM Royal Dutch Airlines",
    "LA – LATAM Airlines",
    "LH – Lufthansa",
    "LO – LOT Polish Airlines",
    "LX – Swiss International Air Lines",
    "LY – El Al Israel Airlines",
    "MA – Malev Hungarian Airlines",
    "MH – Malaysia Airlines",
    "MS – Egyptair",
    "MU – China Eastern Airlines",
    "NH – All Nippon Airways",
    "NW – Northwest Airlines",
    "NZ – Air New Zealand",
    "OK – Czech Airlines",
    "OS – Austrian Airlines",
    "OU – Croatia Airlines",
    "OZ – Asiana Airlines",
    "PK – Pakistan International Airlines",
    "PR – Philippine Airlines",
    "QF – Qantas",
    "QR – Qatar Airways",
    "RJ – Royal Jordanian",
    "SA – South African Airways",
    "SK – Scandinavian Airlines",
    "SQ – Singapore Airlines",
    "SU – Aeroflot",
    "SV – Saudi Arabian Airlines",
    "TG – Thai Airways International",
    "TK – Turkish Airlines",
    "TP – TAP Air Portugal",
    "TW – Trans World Airlines",
    "UA – United Airlines",
    "US – US Airways",
    "UX – Air Europa",
    "VA – Virgin Australia",
    "VS – Virgin Atlantic",
    "VX – Virgin America",
    "WJ – WebJet Linhas Aereas",
    "WN – Southwest Airlines",
    "WS – WestJet",
    "XK – Air Corsica",
    "ZH – Shenzhen Airlines",
    "3K – Jetstar Asia Airways",
    "4U – Germanwings",
    "5J – Cebu Pacific",
    "6E – IndiGo",
    "7C – Jeju Air",
    "8L – Lucky Air",
    "9C – Spring Airlines",
    "9W – Jet Airways",
    "A3 – Aegean Airlines",
    "A5 – HOP!",
    "A7 – Air Plus Comet",
    "A9 – Georgian Airways",
    "AB – Air Berlin",
    "AD – Azul Brazilian Airlines",
    "AE – Mandarin Airlines",
    "AG – Aruba Airlines",
    "AH – Air Algerie",
    "AJ – Aero Contractors",
    "AK – AirAsia",
    "AL – Skyway Airlines",
    "AN – Ansett Australia",
    "AO – Australian Airlines",
    "AP – Air One",
    "AQ – Aloha Airlines",
    "AT – Royal Air Maroc",
    "AU – Austral Lineas Aereas",
    "AW – Schreiner Airways",
    "AX – Trans States Airlines",
    "BB – Seaborne Airlines",
    "BC – Skymark Airlines",
    "BE – Flybe",
    "BF – Bluebird Cargo",
    "BG – Biman Bangladesh Airlines",
    "BH – Hawkair",
    "BK – Potomac Air",
    "BL – Pacific Airlines",
    "BM – Air Sicilia",
    "BN – Braniff International Airways",
    "BO – Bouraq Indonesia Airlines",
    "BP – Air Botswana",
    "BQ – Aeromar",
    "BS – British International Helicopters",
    "BT – Air Baltic",
    "BU – Braathens",
    "BV – Blue Panorama Airlines",
    "BW – Caribbean Airlines",
    "BY – Thomsonfly",
    "BZ – Blue Dart Aviation",
    "C1 – CanJet",
    "C3 – Contact Air",
    "C4 – Conquest Air",
    "C5 – CommutAir",
    "C6 – CanJet Airlines",
    "C7 – Rico Linhas Aereas",
    "C8 – Chicago Express Airlines",
    "C9 – Cirrus Airlines",
    "CB – ScotAirways",
    "CC – Air Atlanta Icelandic",
    "CD – Corendon Dutch Airlines",
    "CE – Nationwide Airlines",
    "CF – City Airline",
    "CG – PNG Air",
    "CH – Bemidji Airlines",
    "CJ – China Northern Airlines",
    "CK – China Cargo Airlines",
    "CL – Lufthansa CityLine",
    "CM – Copa Airlines",
    "CN – Islands Nationair",
    "CP – Canadian Airlines",
    "CQ – Coastal Aviation",
    "CR – OAG",
    "CS – Continental Micronesia",
    "CT – Alitalia CityLiner",
    "CU – Cubana de Aviacion",
    "CV – Air Chathams",
    "CW – Air Marshall Islands",
    "CY – Cyprus Airways",
    "D0 – DHL Air",
    "D1 – DonbassAero",
    "D2 – Severstal Air Company",
    "D3 – Daallo Airlines",
    "D4 – Alidaunia",
    "D5 – DHL Aero Expreso",
    "D6 – Interair South Africa",
    "D7 – AirAsia X",
    "D8 – Norwegian Air International",
    "D9 – Aeroflot-Don",
    "DA – Air Georgia",
    "DB – Brit Air",
    "DC – Golden Air",
    "DD – Nok Air",
    "DE – Condor Flugdienst",
    "DF – Aegean Airlines",
    "DG – South East Asian Airlines",
    "DH – Independence Air",
    "DI – dba",
    "DJ – Virgin Blue",
    "DK – Eastland Air",
    "DM – Maersk Air",
    "DN – Air Deccan",
    "DO – Air Vallee",
    "DP – First Choice Airways",
    "DQ – Coastal Air",
    "DR – Air Link",
    "DS – EasyJet Switzerland",
    "DT – TAAG Angola Airlines",
    "DU – Hemus Air",
    "DV – Nantucket Airlines",
    "DW – Aero-Charter Ukraine",
    "DX – DAT Danish Air Transport",
    "DY – Norwegian Air Shuttle",
    "DZ – Air Metro North",
    "E0 – Eos Airlines",
    "E1 – Usa Sky Cargo",
    "E2 – Eagle Air",
    "E3 – Domodedovo Airlines",
    "E4 – Aero Asia International",
    "E5 – Samara Airlines",
    "E6 – Bringer Air Cargo Taxi Aereo",
    "E7 – Estafeta Carga Aerea",
    "E8 – Alpi Eagles",
    "E9 – Evelop Airlines",
    "EA – Eastern Air Lines",
    "EB – Wamos Air",
    "EC – Avialeasing Aviation Company",
    "ED – Airblue",
    "EE – Aero Airlines",
    "EF – Far Eastern Air Transport",
    "EG – Japan Asia Airways",
    "EH – SAETA",
    "EI – Aer Lingus",
    "EJ – New England Airlines",
    "EL – Air Nippon",
    "EM – Empire Airlines",
    "EN – Air Dolomiti",
    "EO – Hewa Bora Airways",
    "EP – Iran Aseman Airlines",
    "EQ – TAME",
    "ER – Astar Air Cargo",
    "ES – DHL International",
    "EU – Chengdu Airlines",
    "EV – Atlantic Southeast Airlines",
    "EW – Eurowings",
    "EX – Air Santo Domingo",
    "EZ – Evergreen International Airlines",
    "F0 – FlyOne",
    "F1 – Fly Brasil",
    "F2 – Safarilink Aviation",
    "F3 – Flyadeal",
    "F4 – Air Flamenco",
    "F5 – Cosmos Air",
    "F6 – Express Air",
    "F7 – Flybaboo",
    "F8 – Flair Airlines",
    "F9 – Frontier Airlines",
    "FA – Safair",
    "FB – Bulgaria Air",
    "FC – Falcon Air Express",
    "FD – Thai AirAsia",
    "FE – Far Eastern Air Transport",
    "FF – Tower Air",
    "FG – Ariana Afghan Airlines",
    "FH – Freebird Airlines",
    "FK – Keewatin Air",
    "FM – Shanghai Airlines",
    "FN – Regional Air Lines",
    "FO – Felker Air",
    "FP – TAG Aviation",
    "FQ – Brindabella Airlines",
    "FR – Ryanair",
    "FS – Itapemirim Transportes Aereos",
    "FT – FlyEgypt",
    "FU – Air Littoral",
    "FV – Rossiya",
    "FW – Ibex Airlines",
    "FX – FedEx Express",
    "FY – Firefly",
    "FZ – Flydubai",
    "G0 – Ghana International Airlines",
    "G1 – Gorkha Airlines",
    "G2 – Go2Sky",
    "G3 – Gol Transportes Aereos",
    "G4 – Allegiant Air",
    "G5 – China Express Airlines",
    "G6 – Air Volga",
    "G7 – GoJet Airlines",
    "G8 – Go Air",
    "G9 – Air Arabia",
    "GB – Airborne Express",
    "GC – Gambia International Airlines",
    "GD – Air Greenland",
    "GE – TransAsia Airways",
    "GG – Air Guyane Express",
    "GH – Ghana Airways",
    "GI – Itek Air",
    "GJ – Eurofly",
    "GK – Jetstar Japan",
    "GL – Air Greenland",
    "GM – Air Slovakia",
    "GN – Air Gabon",
    "GO – ULS Airlines Cargo",
    "GP – APG Airlines",
    "GQ – Big Sky Airlines",
    "GR – Aurigny Air Services",
    "GS – Tianjin Airlines",
    "GT – GB Airways",
    "GU – Aviateca",
    "GV – Grant Aviation",
    "GW – SkyGreece Airlines",
    "GX – GX Airlines",
    "GY – Colorful Guizhou Airlines",
    "GZ – Air Rarotonga",
    "H1 – Hahn Air Systems",
    "H2 – City Bird",
    "H3 – Harbour Air",
    "H4 – Heli Securite",
    "H5 – Mavial Magadan Airlines",
    "H6 – Hageland Aviation Services",
    "H7 – Eagle Air",
    "H8 – Dalavia",
    "H9 – Pegasus Airlines",
    "HB – Harbour Air",
    "HC – Air Comet",
    "HD – Air Do",
    "HE – LGW Luftfahrtgesellschaft Walter",
    "HF – Hapagfly",
    "HG – Niki",
    "HH – Taban Air",
    "HI – Papillon Airways",
    "HJ – Air Haiti",
    "HK – Four Star Air Cargo",
    "HL – Air Holland",
    "HM – Air Seychelles",
    "HN – Heavylift Cargo Airlines",
    "HO – Juneyao Airlines",
    "HP – America West Airlines",
    "HQ – Thomas Cook Airlines",
    "HR – Hahn Air",
    "HS – Heli Securite",
    "HT – Hellenic Imperial Airways",
    "HV – Transavia Holland",
    "HW – Hello",
    "HX – Hong Kong Airlines",
    "HY – Uzbekistan Airways",
    "HZ – Aurora",
    "I2 – Iberia Express",
    "I3 – FlyArystan",
    "I4 – Island Air Express",
    "I5 – AirAsia India",
    "I6 – Air Indus",
    "I7 – Paramount Airways",
    "I8 – Izhavia",
    "I9 – Air Italy",
    "IA – Iraqi Airways",
    "ID – Batik Air",
    "IE – Solomon Airlines",
    "IF – Fly Baghdad",
    "IG – Meridiana",
    "IH – Irtysh Air",
    "II – IBC Airways",
    "IJ – Spring Airlines Japan",
    "IK – Imair Airlines",
    "IL – Trigana Air Service",
    "IM – Menajet",
    "IN – MAT Macedonian Airlines",
    "IO – IrAero",
    "IP – Atyrau Air Ways",
    "IQ – Augsburg Airways",
    "IR – Iran Air",
    "IS – Air Iceland",
    "IT – Kingfisher Airlines",
    "IU – SW Italia",
    "IV – Wind Jet",
    "IW – Wings Air",
    "IX – Air India Express",
    "IY – Yemenia",
    "IZ – Arkia Israel Airlines",
    "J0 – Jetlink Express",
    "J1 – One Jet",
    "J2 – Azerbaijan Airlines",
    "J3 – Northwestern Air",
    "J4 – Buffalo Airways",
    "J5 – Alaska Seaplane Service",
    "J6 – Jet Ops",
    "J7 – Centre-Avia",
    "J8 – Berjaya Air",
    "J9 – Jazeera Airways",
    "JA – B&H Airlines",
    "JB – Helijet",
    "JC – JAL Express",
    "JD – Beijing Capital Airlines",
    "JE – Mango",
    "JF – Jetairfly",
    "JG – JetGo Australia",
    "JH – Fuji Dream Airlines",
    "JI – Meraj Air",
    "JJ – LATAM Brasil",
    "JK – Spanair",
    "JM – Air Jamaica",
    "JN – Excel Airways",
    "JO – JALways",
    "JP – Adria Airways",
    "JQ – Jetstar Airways",
    "JR – Aero California",
    "JS – Air Koryo",
    "JT – Lion Air",
    "JU – Air Serbia",
    "JV – Bearskin Lake Air Service",
    "JW – Arrow Air",
    "JX – Starlux Airlines",
    "JY – InterCaribbean Airways",
    "JZ – Skyways Express",
    "K1 – Topas Co Ltd",
    "K2 – EuroLOT",
    "K3 – Taquan Air",
    "K4 – Kalitta Charters",
    "K5 – SeaPort Airlines",
    "K6 – Cambodia Angkor Air",
    "K7 – Air KBZ",
    "K8 – Kan Air",
    "K9 – Krylo Aviakompania",
    "KB – Druk Air",
    "KC – Air Astana",
    "KD – Kalstar Aviation",
    "KF – Blue1",
    "KG – Key Lime Air",
    "KH – Kyrgyzstan",
    "KI – Adam Air",
    "KJ – British Mediterranean Airways",
    "KK – AtlasGlobal",
    "KM – Air Malta",
    "KN – China United Airlines",
    "KO – Komiaviatrans State Air Enterprise",
    "KP – Kiwi International Air Lines",
    "KR – Air Bishkek",
    "KS – Penair",
    "KT – Silk Way Airlines",
    "KU – Kuwait Airways",
    "KV – Kavminvodyavia",
    "KW – Kelowna Flightcraft Air Charter",
    "KX – Cayman Airways",
    "KY – Air Sao Tome and Principe",
    "KZ – Nippon Cargo Airlines",
    "L0 – Lynden Air Cargo",
    "L1 – Lynden Air Cargo",
    "L2 – Lynden Air Cargo",
    "L3 – Lynden Air Cargo",
    "L4 – Lynden Air Cargo",
    "L5 – Atlantique Air Assistance",
    "L6 – Tbilaviamsheni",
    "L7 – Laoag International Airlines",
    "L8 – Line Blue",
    "L9 – Belle Air",
    "LB – Lloyd Aereo Boliviano",
    "LC – Varig Log",
    "LD – Air Hong Kong",
    "LE – LOT Polish Airlines",
    "LF – Contour Airlines",
    "LG – Luxair",
    "LI – LIAT",
    "LJ – Jin Air",
    "LK – Air Lituanica",
    "LL – Miami Air International",
    "LM – Loganair",
    "LN – Libyan Airlines",
    "LP – LAN Peru",
    "LQ – Lanmei Airlines",
    "LR – Avianca Costa Rica",
    "LS – Jet2.com",
    "LT – Air Lituanica",
    "LU – LAN Express",
    "LV – MEGA Maldives",
    "LW – Pacific Wings",
    "LZ – Belle Air Europe",
    "M0 – Aero Mongolia",
    "M1 – Mango",
    "M2 – MHS Aviation",
    "M3 – North Flying",
    "M4 – Mistral Air",
    "M5 – Kenmore Air",
    "M6 – Amerijet International",
    "M7 – Marsland Aviation",
    "M8 – Medsky Airways",
    "M9 – Motor Sich Airlines",
    "MB – Execaire",
    "MC – Air Mobility Command",
    "MD – Air Madagascar",
    "ME – Middle East Airlines",
    "MF – Xiamen Airlines",
    "MG – Champion Air",
    "MI – SilkAir",
    "MJ – Mihin Lanka",
    "MK – Air Mauritius",
    "ML – Air Mediterranee",
    "MM – SAM Colombia",
    "MN – Kulula",
    "MO – Calm Air",
    "MP – Martinair",
    "MQ – American Eagle Airlines",
    "MR – Air Mauritanie",
    "MT – Thomas Cook Airlines",
    "MV – Armavia",
    "MW – Maya Island Air",
    "MX – Mexicana de Aviacion",
    "MY – Air Mali",
    "MZ – Merpati Nusantara Airlines",
    "N0 – North American Airlines",
    "NA – National Airlines",
    "NC – Northern Air Cargo",
    "NK – Spirit Airlines",
    "NW – Northwest Airlines",
    "O0 – Not assigned",
    "O1 – Not assigned",
    "O2 – Not assigned",
    "O3 – Not assigned",
    "O4 – Not assigned",
    "O5 – Not assigned",
    "O6 – Not assigned",
    "O7 – Not assigned",
    "O8 – Not assigned",
    "O9 – Not assigned",
    "OA – Olympic Air",
    "OB – Not assigned",
    "OC – Not assigned",
    "OD – Not assigned",
    "OE – Not assigned",
    "OF – Not assigned",
    "OG – Not assigned",
    "OH – Not assigned",
    "OI – Not assigned",
    "OJ – Not assigned",
    "OL – Not assigned",
    "OM – Not assigned",
    "ON – Not assigned",
    "OO – Not assigned",
    "OP – Not assigned",
    "OQ – Not assigned",
    "OR – Not assigned",
    "OT – Not assigned",
    "OV – Not assigned",
    "OW – Not assigned",
    "OX – Not assigned",
    "OY – Not assigned",
    "P0 – Proflight Zambia",
    "P1 – Not assigned",
    "P2 – Not assigned",
    "P3 – Not assigned",
    "P4 – Not assigned",
    "P5 – Not assigned",
    "P6 – Not assigned",
    "P7 – Not assigned",
    "P8 – Not assigned",
    "P9 – Not assigned",
    "PA – Pan American World Airways",
    "PB – Not assigned",
    "PC – Not assigned",
    "PD – Not assigned",
    "PE – Not assigned",
    "PF – Not assigned",
    "PG – Not assigned",
    "PH – Not assigned",
    "PI – Not assigned",
    "PJ – Not assigned",
    "PL – Not assigned",
    "PM – Not assigned",
    "PN – Not assigned",
    "PO – Not assigned",
    "PP – Not assigned",
    "PQ – Not assigned",
    "PS – Not assigned",
    "PT – Not assigned",
    "PU – Not assigned",
    "PV – Not assigned",
    "PW – Not assigned",
    "PX – Not assigned",
    "PY – Not assigned",
    "PZ – Not assigned",
    "Q0 – Not assigned",
    "Q1 – Not assigned",
    "Q2 – Not assigned",
    "Q3 – Not assigned",
    "Q4 – Not assigned",
    "Q5 – Not assigned",
    "Q6 – Not assigned",
    "Q7 – Not assigned",
    "Q8 – Not assigned",
    "Q9 – Not assigned",
    "QA – Not assigned",
    "QB – Not assigned",
    "QC – Not assigned",
    "QD – Not assigned",
    "QE – Not assigned",
    "QG – Not assigned",
    "QH – Not assigned",
    "QI – Not assigned",
    "QJ – Not assigned",
    "QK – Not assigned",
    "QL – Not assigned",
    "QM – Not assigned",
    "QN – Not assigned",
    "QO – Not assigned",
    "QP – Not assigned",
    "QQ – Not assigned",
    "QS – Not assigned",
    "QT – Not assigned",
    "QU – Not assigned",
    "QV – Not assigned",
    "QW – Not assigned",
    "QX – Not assigned",
    "QY – Not assigned",
    "QZ – Not assigned",
    "R0 – Royal Airlines",
    "R1 – Not assigned",
    "R2 – Not assigned",
    "R3 – Not assigned",
    "R4 – Not assigned",
    "R5 – Not assigned",
    "R6 – Not assigned",
    "R7 – Not assigned",
    "R8 – Not assigned",
    "R9 – Not assigned",
    "RA – Royal Nepal Airlines",
    "RB – Not assigned",
    "RC – Not assigned",
    "RD – Not assigned",
    "RE – Not assigned",
    "RF – Not assigned",
    "RG – Not assigned",
    "RH – Not assigned",
    "RK – Not assigned",
    "RL – Not assigned",
    "RM – Not assigned",
    "RN – Not assigned",
    "RO – Not assigned",
    "RP – Not assigned",
    "RQ – Not assigned",
    "RR – Not assigned",
    "RS – Not assigned",
    "RT – Not assigned",
    "RU – Not assigned",
    "RV – Not assigned",
    "RW – Not assigned",
    "RX – Not assigned",
    "RY – Not assigned",
    "RZ – Not assigned",
    "S0 – Not assigned",
    "S1 – Not assigned",
    "S2 – Not assigned",
    "S3 – Not assigned",
    "S4 – Not assigned",
    "S5 – Not assigned",
    "S6 – Not assigned",
    "S7 – Not assigned",
    "S8 – Not assigned",
    "S9 – Not assigned",
    "SB – Not assigned",
    "SC – Not assigned",
    "SD – Not assigned",
    "SE – Not assigned",
    "SF – Not assigned",
    "SG – Not assigned",
    "SH – Not assigned",
    "SI – Not assigned",
    "SJ – Not assigned",
    "SL – Not assigned",
    "SM – Not assigned",
    "SN – Not assigned",
    "SO – Not assigned",
    "SP – Not assigned",
    "SR – Not assigned",
    "SS – Not assigned",
    "ST – Not assigned",
    "SW – Not assigned",
    "SX – Not assigned",
    "SY – Not assigned",
    "SZ – Not assigned",
    "T0 – Not assigned",
    "T1 – Not assigned",
    "T2 – Not assigned",
    "T3 – Not assigned",
    "T4 – Not assigned",
    "T5 – Not assigned",
    "T6 – Not assigned",
    "T7 – Not assigned",
    "T8 – Not assigned",
    "T9 – Not assigned",
    "TA – TACA Airlines",
    "TB – Not assigned",
    "TC – Not assigned",
    "TD – Not assigned",
    "TE – Not assigned",
    "TF – Not assigned",
    "TH – Not assigned",
    "TI – Not assigned",
    "TJ – Not assigned",
    "TL – Not assigned",
    "TM – Not assigned",
    "TN – Not assigned",
    "TO – Not assigned",
    "TQ – Not assigned",
    "TR – Not assigned",
    "TS – Not assigned",
    "TT – Not assigned",
    "TU – Not assigned",
    "TV – Not assigned",
    "TX – Not assigned",
    "TY – Not assigned",
    "TZ – Not assigned",
    "U0 – Not assigned",
    "U1 – Not assigned",
    "U2 – Not assigned",
    "U3 – Not assigned",
    "U4 – Not assigned",
    "U5 – Not assigned",
    "U6 – Not assigned",
    "U7 – Not assigned",
    "U8 – Not assigned",
    "U9 – Not assigned",
    "UB – Not assigned",
    "UC – Not assigned",
    "UD – Not assigned",
    "UE – Not assigned",
    "UF – Not assigned",
    "UG – Not assigned",
    "UH – Not assigned",
    "UI – Not assigned",
    "UJ – Not assigned",
    "UK – Not assigned",
    "UL – Not assigned",
    "UM – Not assigned",
    "UN – Not assigned",
    "UO – Not assigned",
    "UP – Not assigned",
    "UQ – Not assigned",
    "UR – Not assigned",
    "UT – Not assigned",
    "UU – Not assigned",
    "UV – Not assigned",
    "UW – Not assigned",
    "UY – Not assigned",
    "UZ – Not assigned",
    "V0 – Not assigned",
    "V1 – Not assigned",
    "V2 – Not assigned",
    "V3 – Not assigned",
    "V4 – Not assigned",
    "V5 – Not assigned",
    "V6 – Not assigned",
    "V7 – Not assigned",
    "V8 – Not assigned",
    "V9 – Not assigned",
    "VB – Not assigned",
    "VC – Not assigned",
    "VD – Not assigned",
    "VE – Not assigned",
    "VF – Not assigned",
    "VG – Not assigned",
    "VH – Not assigned",
    "VI – Not assigned",
    "VJ – Not assigned",
    "VK – Not assigned",
    "VL – Not assigned",
    "VM – Not assigned",
    "VN – Vietnam Airlines",
    "VO – Not assigned",
    "VP – Not assigned",
    "VQ – Not assigned",
    "VR – Not assigned",
    "VT – Not assigned",
    "VU – Not assigned",
    "VV – Not assigned",
    "VW – Not assigned",
    "VY – Not assigned",
    "VZ – Not assigned",
    "W0 – Not assigned",
    "W1 – Not assigned",
    "W2 – Not assigned",
    "W3 – Not assigned",
    "W4 – Not assigned",
    "W5 – Not assigned",
    "W6 – Not assigned",
    "W7 – Not assigned",
    "W8 – Not assigned",
    "W9 – Not assigned",
    "WA – Not assigned",
    "WB – Not assigned",
    "WC – Not assigned",
    "WD – Not assigned",
    "WE – Not assigned",
    "WF – Not assigned",
    "WG – Not assigned",
    "WH – Not assigned",
    "WI – Not assigned",
    "WK – Not assigned",
    "WL – Not assigned",
    "WM – Not assigned",
    "WO – Not assigned",
    "WP – Not assigned",
    "WQ – Not assigned",
    "WR – Not assigned",
    "WT – Not assigned",
    "WU – Not assigned",
    "WV – Not assigned",
    "WW – Not assigned",
    "WX – Not assigned",
    "WY – Not assigned",
    "WZ – Not assigned",
    "X0 – Not assigned",
    "X1 – Not assigned",
    "X2 – Not assigned",
    "X3 – Not assigned",
    "X4 – Not assigned",
    "X5 – Not assigned",
    "X6 – Not assigned",
    "X7 – Not assigned",
    "X8 – Not assigned",
    "X9 – Not assigned",
    "XA – Not assigned",
    "XB – Not assigned",
    "XC – Not assigned",
    "XD – Not assigned",
    "XE – Not assigned",
    "XF – Not assigned",
    "XG – Not assigned",
    "XH – Not assigned",
    "XI – Not assigned",
    "XJ – Not assigned",
    "XL – Not assigned",
    "XM – Not assigned",
    "XN – Not assigned",
    "XO – Not assigned",
    "XP – Not assigned",
    "XQ – Not assigned",
    "XR – Not assigned",
    "XS – Not assigned",
    "XT – Not assigned",
    "XU – Not assigned",
    "XV – Not assigned",
    "XW – Not assigned",
    "XX – Not assigned",
    "XY – Not assigned",
    "XZ – Not assigned",
    "Y0 – Not assigned",
    "Y1 – Not assigned",
    "Y2 – Not assigned",
    "Y3 – Not assigned",
    "Y4 – Not assigned",
    "Y5 – Not assigned",
    "Y6 – Not assigned",
    "Y7 – Not assigned",
    "Y8 – Not assigned",
    "Y9 – Not assigned",
    "YA – Not assigned",
    "YB – Not assigned",
    "YC – Not assigned",
    "YD – Not assigned",
    "YE – Not assigned",
    "YF – Not assigned",
    "YG – Not assigned",
    "YH – Not assigned",
    "YI – Not assigned",
    "YJ – Not assigned",
    "YK – Not assigned",
    "YL – Not assigned",
    "YM – Not assigned",
    "YN – Not assigned",
    "YO – Not assigned",
    "YP – Not assigned",
    "YQ – Not assigned",
    "YR – Not assigned",
    "YS – Not assigned",
    "YT – Not assigned",
    "YU – Not assigned",
    "YV – Not assigned",
    "YW – Not assigned",
    "YX – Not assigned",
    "YY – Not assigned",
    "YZ – Not assigned",
    "Z0 – Not assigned",
    "Z1 – Not assigned",
    "Z2 – Not assigned",
    "Z3 – Not assigned",
    "Z4 – Not assigned",
    "Z5 – Not assigned",
    "Z6 – Not assigned",
    "Z7 – Not assigned",
    "Z8 – Not assigned",
    "Z9 – Not assigned",
    "ZA – Not assigned",
    "ZB – Not assigned",
    "ZC – Not assigned",
    "ZD – Not assigned",
    "ZE – Not assigned",
    "ZF – Not assigned",
    "ZG – Not assigned",
    "ZI – Not assigned",
    "ZJ – Not assigned",
    "ZK – Not assigned",
    "ZL – Not assigned",
    "ZM – Not assigned",
    "ZN – Not assigned",
    "ZO – Not assigned",
    "ZP – Not assigned",
    "ZQ – Not assigned",
    "ZR – Not assigned",
    "ZS – Not assigned",
    "ZT – Not assigned",
    "ZU – Not assigned",
    "ZV – Not assigned",
    "ZW – Not assigned",
    "ZX – Not assigned",
    "ZY – Not assigned",
    "ZZ – Not assigned"
] 